import { HttpStatus } from '@nestjs/common'

export const STATUS_CODES: { [key: string]: string } = {
  [HttpStatus.CONTINUE]: '请求继续',
  [HttpStatus.SWITCHING_PROTOCOLS]: '协议切换',
  [HttpStatus.PROCESSING]: '处理中',
  [HttpStatus.OK]: '请求成功',
  [HttpStatus.CREATED]: '请求已创建',
  [HttpStatus.ACCEPTED]: '请求已接受',
  [HttpStatus.NON_AUTHORITATIVE_INFORMATION]: '非授权信息',
  [HttpStatus.NO_CONTENT]: '无内容',
  [HttpStatus.RESET_CONTENT]: '重置内容',
  [HttpStatus.PARTIAL_CONTENT]: '部分内容',
  [HttpStatus.MOVED_PERMANENTLY]: '永久移动',
  [HttpStatus.FOUND]: '临时移动',
  [HttpStatus.SEE_OTHER]: '参见其他',
  [HttpStatus.NOT_MODIFIED]: '内容未修改',
  [HttpStatus.TEMPORARY_REDIRECT]: '临时重定向',
  [HttpStatus.PERMANENT_REDIRECT]: '永久重定向',
  [HttpStatus.BAD_REQUEST]: '错误请求',
  [HttpStatus.UNAUTHORIZED]: '未授权',
  [HttpStatus.PAYMENT_REQUIRED]: '需要付款',
  [HttpStatus.FORBIDDEN]: '禁止访问',
  [HttpStatus.NOT_FOUND]: '未找到资源',
  [HttpStatus.METHOD_NOT_ALLOWED]: '此方法不允许',
  [HttpStatus.NOT_ACCEPTABLE]: '不可接受',
  [HttpStatus.PROXY_AUTHENTICATION_REQUIRED]: '代理认证要求',
  [HttpStatus.REQUEST_TIMEOUT]: '请求超时',
  [HttpStatus.CONFLICT]: '存在冲突',
  [HttpStatus.GONE]: '已删除',
  [HttpStatus.LENGTH_REQUIRED]: '要求请求长度',
  [HttpStatus.PRECONDITION_FAILED]: '前置条件失败',
  [HttpStatus.PAYLOAD_TOO_LARGE]: '请求实体过大',
  [HttpStatus.URI_TOO_LONG]: '请求URI过长',
  [HttpStatus.UNSUPPORTED_MEDIA_TYPE]: '不支持的媒体类型',
  [HttpStatus.REQUESTED_RANGE_NOT_SATISFIABLE]: '请求范围无法满足',
  [HttpStatus.EXPECTATION_FAILED]: '期望失败',
  [HttpStatus.I_AM_A_TEAPOT]: '我是茶壶', // RFC 2324，彩蛋
  [HttpStatus.UNPROCESSABLE_ENTITY]: '无法处理的实体',
  [HttpStatus.FAILED_DEPENDENCY]: '依赖失败',
  [HttpStatus.PRECONDITION_REQUIRED]: '要求前置条件',
  [HttpStatus.TOO_MANY_REQUESTS]: '请求过多',
  [HttpStatus.INTERNAL_SERVER_ERROR]: '服务器错误',
  [HttpStatus.NOT_IMPLEMENTED]: '未实现',
  [HttpStatus.BAD_GATEWAY]: '网关错误',
  [HttpStatus.SERVICE_UNAVAILABLE]: '服务暂不可用',
  [HttpStatus.GATEWAY_TIMEOUT]: '网关超时',
  [HttpStatus.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP版本不支持',
}
